### ISSUE TITLE
GPS info is not sent out on ZMQ socket

### ISSUE THREAD

**Issue by jonakarl** [kristrev/data-exporter#5]
I can see debug output about GPS positions but I never get any output on the ZMQ socket (modem updates I do get). 
### Parameters

```
ps auxf|grep nl
root       540  0.0  0.1 119580  4780 ?        Sl   Nov30   0:16  \_ meta_exporter -n --nl_conn --nl_pos -s --sql_database=/tmp/metadata.db --sql_meta_prefix=/tmp/metatemp --sql_nodeid=113 -z --zmq_address 127.0.0.1 --zmq_port 5556
```
### deb package

```
dpkg -s metadata-exporter 
Package: metadata-exporter
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 73
Maintainer: Kristian R. Evensen <kristrev@celerway.com>
Architecture: amd64
Version: 0.1.0
Depends: libc6 (>= 2.14), libgps21 (>= 3.3), libjson-c2 (>= 0.10), libmnl0 (>= 1.0.3-4~), libsqlite3-0 (>= 3.7.15), dlb (>= 0.1.0), jq (>= 1.4), curl (>= 7.38), libsodium13 (>= 1.0), libzmq (>= 5.0), gpsd (>= 3.11)
Description: meta_exporter built using CMake
```
## This is what I tried:

```
monroe@Monroe-X:~/test/examples/zeromq$ date;python sub.py ;date
Tue Dec  1 07:51:14 CET 2015
MONROE.META.DEVICE.MODEM.UPDATE {"seq":4673,"tstamp":1448952696,"interface_id":"89460120140506984433","interface_name":"wwan0","operator":24001,"mode":6,"signal_strength":-62}
MONROE.META.DEVICE.MODEM.UPDATE {"seq":4675,"tstamp":1448952726,"interface_id":"89460120140506984433","interface_name":"wwan0","operator":24001,"mode":6,"signal_strength":-62}
MONROE.META.DEVICE.MODEM.UPDATE {"seq":4677,"tstamp":1448952756,"interface_id":"89460120140506984433","interface_name":"wwan0","operator":24001,"mode":6,"signal_strength":-62}
KeyboardInterrupt
Tue Dec  1 07:52:42 CET 2015
monroe@Monroe-X:~/test/examples/zeromq$ cat /var/log/network-listener.log|grep nmea|tail -20
(07:51:48.060) [DEBUG]: qmi_lib/PdsChannel.cpp sendNmea 300 Will send: {"timestamp":1448952708,"event_type":4,"nmea_string":"$GPGGA,065203.0,5924.250439,N,01334.899118,E,1,05,1.5,139.1,M,35.0,M,,*55\r\n"}
(07:51:48.124) [DEBUG]: qmi_lib/PdsChannel.cpp sendNmea 300 Will send: {"timestamp":1448952708,"event_type":4,"nmea_string":"$GPRMC,065203.0,A,5924.250439,N,01334.899118,E,0.0,231.5,011215,0.0,E,A*02\r\n"}
```

I also tried to hook up to the netlink socket directly but it is similar situation there, I only get modem information.

**Comment by kristrev** [comment]
You have not posted the code you use for reading the GPS.

**Comment by jonakarl** [comment]
Is this what you are looking for ?

Reading zmq socket: 

```
cat zeromq/sub.py 
import zmq

context = zmq.Context()
socket = context.socket(zmq.SUB)
#socket.connect ("tcp://localhost:5556")
socket.connect ("tcp://127.0.0.1:5556")

#  Empty string is everything
topicfilter = ''
socket.setsockopt(zmq.SUBSCRIBE, topicfilter)

while True:
    string = socket.recv()
    print string
    #topic, messagedata = string.split()
    #print "%s %s" % (topic, messagedata)
```

I also read the netlink socket (however this code is a bit experimental and only used for debug purposes): 

```
cat nl_listener.py 
#!/usr/bin/python

import pymnl
import pymnl.nlsocket
import json 

#(netlink_helpers.c) nlhelper_create_socket( NETLINK_USERSOCK,(1 << (METADATA_NL_GROUP - 1)) )

METADATA_NL_GROUP=0x03
sock = pymnl.nlsocket.Socket(pymnl.NETLINK_USERSOCK)
sock.bind(0, (1 << (METADATA_NL_GROUP - 1)) )

while True:
    nlmsgs = sock.recv()
    for nlmsg in nlmsgs:
        msgdata =  nlmsg.get_payload().get_data()
        #msgdata =  nlmsg.get_payload().get_binary()
        # Is there a cleaner way to get rid of junk data, TODO: look how Kristian does it
        msgdata = msgdata[msgdata.find('{'):msgdata.rfind('}')+1]
        try:
            msg = json.loads(msgdata)
            print str(msg)
        except ValueError as e:
            print "err no json : "  + str(e) + " msg : "  + msgdata
            continue
```

**Comment by kristrev** [comment]
Do you have a fix? What is the gps source?

**Comment by jonakarl** [comment]
Gps source: sierra
Fix: no, but i guess either metadata-exporter never recives the data
(probable as I also do not see the json on the netlink socket) or metadata
exporter never retransmit it on zmq.

Network-listener (one of your closed source core components?) recive data
and according to the debug message also sends it out. I have done no more
debugging as I have no source and no system design of how your core
components interact and who reads what.
I could probably do some reveerse Engineering to find that out but that
might be a ipr violation so I have avoided that ;-).

Jonas Karlsson
Senior Research Engineer

Karlstad University
SE-651 88 Karlstad, Sweden
Telephone: +46 54 700 15 64
Mobile: +46 70 672 06 20
Skype: karlsson.karl.jonas
Hangout: karlsson.karl.jonas
GPG/PGP : E92574EFCE8AB0B3

twitter.com/kau
facebook.com/karlstadsuniversitet
KAU.SE
Den 1 dec 2015 08:53 skrev "Kristian Evensen" notifications@github.com:

**Comment by kristrev** [comment]
GPS is only exported when you have a fix. For testing you can use the test mode of the exporter. Remeber to specify tye correcr input/writer as well.

**Comment by jonakarl** [comment]
We should have a gps fix right since we get gps info in the
network-listener log, or did I miss your point?

Jonas Karlsson
Senior Research Engineer

Karlstad University
SE-651 88 Karlstad, Sweden
Telephone: +46 54 700 15 64
Mobile: +46 70 672 06 20
Skype: karlsson.karl.jonas
Hangout: karlsson.karl.jonas
GPG/PGP : E92574EFCE8AB0B3

twitter.com/kau
facebook.com/karlstadsuniversitet
KAU.SE
Den 2 dec 2015 8:46 fm skrev "Kristian Evensen" notifications@github.com:

**Comment by kristrev** [comment]
Do you see co-ordinates in GPS lines in the network listener log file?

**Comment by jonakarl** [comment]
Yes, see first post from me under heading "This is what I tried:"

I have also double checked this today and in the network-listener.log there are several sendNmea lines (with coordinates) while I only get modem output on zmq socket (similar as in my first post). 
I also let the zmq subscriber run for acouple of hours so there was no lag issues between the network-listener debug and when information was recived on zmq but no gps inof is sent at all on zmq.

**Comment by kristrev** [comment]
Have you specified correct input/writer? Not looked at GPS for a while, so can't remember which ones. Ask Thomas or jonas, maybe they know.

**Comment by jonakarl** [comment]
I think so, this is the command it is started with (see first post) 
meta_exporter -n --nl_conn --nl_pos -s --sql_database=/tmp/metadata.db --sql_meta_prefix=/tmp/metatemp --sql_nodeid=113 -z --zmq_address 127.0.0.1 --zmq_port 5556

--nl_pos turn on gps input,  right?
--zmq turn on zmq output, right?

I will also send a question to Jonas W and Thomas AND ask if they know.

**Comment by kristrev** [comment]
Yes, this is correct. If no solution is found, I will try to have a look next week but can't give any guarantee that I will have time.

**Comment by relet** [comment]
The error was with the netlink group used by network listener. Fixing it there, and a new package is on the way.
